export const tableUsers  =[{
  id_agent_token:"1234", 
  id:"01",
  email:"agent@email",
  name:"Agent outsider",
  user_name:"agent",
  description:"Hellow iam a agent that belive that techinology can help the world be a better place.😎",
  balance: 1500,
  is_active:true,
  level:2,
  image_profile:'../../assets/images/imgProgile.jpg',
  vocation:"Technology",
  state: 2
},
{
  id_agent_token:"1234", 
  id:"02",
  email:"agent2@email",
  name:" Deb  Linds",
  user_name:"agent",
  description:"I love help people find your propose of life 👩‍🏫",
  balance: 3700,
  is_active:true,
  level:2,
  image_profile:'../../assets/images/avatar.png',
  vocation:"Teacher",
  state: 1
},
{
  id_agent_token:"1234", 
  id:"03",
  email:"agent3@email",
  name:" John Arthur ",
  user_name:"johnjohn",
  description:"I am  lawyer and  fight to right humans.",
  balance: 3700,
  is_active:true,
  level:2,
  image_profile:'../../assets/images/avatar.png',
  vocation:"Right Humans",
  state: 1
},
{
  id_agent_token:"1234", 
  id:"04",
  email:"agent4@email",
  name:" Luke Doller",
  user_name:"lukedoller",
  description:"At moment i am working with new course of share more information about green life.",
  balance: 700,
  is_active:true,
  level:4,
  image_profile:'../../assets/images/avatar.png',
  vocation:"Biology",
  state: 4
},
]